### ISSUE TITLE
Unable to run bin/run-ghcid.sh

### ISSUE THREAD

**Issue by morucci** [ButlerOS/haskell-butler#49]
Since the modules reorganization I can no longer run that script.

```
<interactive>:28:1: error: [GHC-76037]
    Not in scope: ‘ButlerDemos.multiDesktop’
    NB: no module named ‘ButlerDemos’ is imported.

...done
```

I used to use it to dev on the demoSocialLogin app with: ./bin/run-ghcid ButlerDemos.demoSocialAuth and it does not seem to work anymore.

**Comment by TristanCacqueray** [comment]
That's odd, it's working fine here. Are you using the HEAD (aefb166) ? When starting the command, does it shows:

```ShellSession
$ ./bin/run-ghcid ButlerDemos.demoSocialAuth 

Loading ./bin/repl ...
Build profile: -w ghc-9.6.2 -O1
```

**Comment by morucci** [comment]
Yes and Yes. However I see this too: "Command is not supported (yet) in multi-mode"

**Comment by morucci** [comment]
[nix(butler)] cabal --version
cabal-install version 3.11
compiled using version 3.11.0.0 of the Cabal library 
[nix(butler)] ghcid --version
Auto reloading GHCi daemon v0.8.9

**Comment by morucci** [comment]
[nix(butler)] git log -n 1
commit aefb166090cf4348a7501ba0ecbbd5b2ce6e2314 (HEAD -> main, origin/main, origin/HEAD)

**Comment by morucci** [comment]
Let's look at that tomorrow together that will be easier perhaps.

**Comment by TristanCacqueray** [comment]
Could you try to `rm -Rf dist-newstyle/ .ghc.environment*`

**Comment by morucci** [comment]
I did it but still I get the same error.

**Comment by TristanCacqueray** [comment]
Ok, it appears to be a cabal issue. When running with `--verbose`, we observed that the `-unit` arguments are not in the correct order on your system. For now, when this issue happens, the workaround is to:
- Run cabal repl with `--verbose --keep-temp-files` to grab the `ghc --interactive` invocation command.
- Swap the `-unit` arguments to match the desired order (e.g. make sure `butler-desktop` is after `butler`)
- Run ghcid like this:

```ShellSession
$ ghcid --command "ghc --interactive -package-env - -j 'NumJobs (Just 8)'
    -unit '@.../dist-newstyle/multi-out-51828/butler-0.1-inplace'
    -unit '@.../multi-out-51828/butler-0.1-inplace-butler-desktop'" --test ButlerDemos.main
```
